import Footer from "@/components/ui/footer";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
// import ModalProvider from "@/components/providers/modal-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";
const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meal planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <EdgeStoreProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${inter.className} bg-slate-50 dark:bg-neutral-900`}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
              storageKey="mealplanner"
            >
              <Navbar />
              {children}
              <Toaster />
              <Footer />
            </ThemeProvider>
          </body>
        </html>
      </EdgeStoreProvider>
    </ClerkProvider>
  );
}
